### ISSUE TITLE
smileInComment.user.js 在加了 .SidePanel.png_bg 后收藏盒不能用了

### ISSUE THREAD

**Issue by inchei** [shadowdreamer/jioben#3]
上次PR时没有注意到这个问题，不好意思
但是我想不通是为什么(bgm38)帮忙看一看行吗

**Comment by shadowdreamer** [comment]
收藏盒是哪儿的功能(bgm38)

**Comment by inchei** [comment]
抱歉这么晚回复，收藏盒：
![收藏盒.PNG](https://i.loli.net/2019/08/31/y2uIc5LDpOmvAgB.png)
这是没有登陆时的画面，登陆并启用脚本后这里会改不了评分

**Comment by shadowdreamer** [comment]
@inchei 我这里启用后可以改评分，请问是什么浏览器？有没有可能是其他脚本干扰了？
